# Generated by Django 2.1.7 on 2019-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(default='null', max_length=50)),
                ('name', models.CharField(default='null', max_length=50)),
                ('age', models.IntegerField()),
                ('details', models.TextField(null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('number', models.CharField(default='0', max_length=50)),
                ('img_user', models.CharField(default='', max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.CharField(max_length=100)),
                ('result_to', models.CharField(default='', max_length=100)),
                ('confirm_del', models.IntegerField(default=0)),
                ('details', models.TextField(default='')),
            ],
            options={
                'db_table': 'user_file',
            },
        ),
    ]
