# Generated by Django 2.1.7 on 2019-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='HospitalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'hospital_admin',
            },
        ),
        migrations.CreateModel(
            name='HospitalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('number', models.CharField(default='0', max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('upload_to', models.CharField(max_length=100)),
                ('result_to', models.CharField(default='', max_length=100)),
                ('img_user', models.CharField(default='', max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('confirm_del', models.IntegerField(default=0)),
                ('details', models.TextField(default='')),
            ],
            options={
                'db_table': 'hospital_file',
            },
        ),
    ]
