# Generated by Django 2.1.5 on 2019-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='h_add',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='h_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
