# Generated by Django 2.1.7 on 2019-04-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalfile',
            name='data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
